export default {
    THEME_CHANGE: "THEMEN_CHANGE",
    THEME_INIT: "THEME_INIT",
    POPULAT_REFRESH:"POPULAT_REFRESH",
    LOAD_POPULAT_FAIL:"LOAD_POPULAT_FAIL",
    LOAD_POPULAT_SUCCESS:"LOAD_POPULAT_SUCCESS",
}